service:
  name: knowid-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  environment:
    MONGO_DB_URL: ${env:MONGO_DB_URL}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  webpack:
    includeModules: true

package:
  individually: true

functions:
  index:
    handler: src/index.handler
    events:
      - http:
          cors: true
          path: '{any+}'
          method: any
